[pytest]
pythonpath = .
asyncio_mode = auto
testpaths = tests
env =
    DATABASE_URL=sqlite:///./test_system.db
    SECRET_KEY=test_secret_key_12345
    ENCRYPTION_KEY=FbfA95Ns7rrcSJHNpXGLSWNH1jFB1FU6Bxlk-UiWEyI=
    REDIS_URL=redis://localhost:6379/1
