from typing import Tuple
from olt_cli_backup import OltCliProfile, run_olt_cli_backup


MAXPRINT_PROFILE = OltCliProfile(
    vendor_name="OLT Maxprint",
    paging_commands=(
        "terminal length 0",
        "terminal width 512",
        "no page",
        "no paging",
        "terminal pager 0",
        "screen-length 0",
        "terminal datadump",
    ),
    backup_commands=(
        "show saved-config",
        "backup config",
        "backup startup-config",
        "backup saved-config",
        "show running-config",
        "show running-config all",
        "show startup-config",
        "show configuration",
        "show config",
        "show run",
        "show running",
        "show running config",
        "show startup config",
        "show system-config",
        "display current-configuration",
        "cat /config/running-config",
        "cat /tmp/running-config",
        "more /config/running-config",
    ),
    config_markers=(
        "hostname ",
        "interface ",
        "vlan ",
        "gpon",
        "epon",
        "pon ",
        "onu ",
        "ont ",
        "service-port",
        "traffic-profile",
        "dba-profile",
        "line-profile",
        "profile ",
        "snmp-server",
        "qos",
        "end",
    ),
    command_timeout_seconds=420,
    max_backup_attempts=0,
    failure_probe_timeout_seconds=8,
)


def realizar_backup(
    ip: str,
    usuario: str,
    porta: int,
    nome_provedor: str,
    nome_tipo_equip: str,
    nome_dispositivo: str,
    parametros: dict = None,
    task_id: str = None,
    backup_base_path: str = None,
    **kwargs,
) -> Tuple:
    return run_olt_cli_backup(
        profile=MAXPRINT_PROFILE,
        ip=ip,
        usuario=usuario,
        porta=porta,
        nome_provedor=nome_provedor,
        nome_tipo_equip=nome_tipo_equip,
        nome_dispositivo=nome_dispositivo,
        parametros=parametros,
        task_id=task_id,
        backup_base_path=backup_base_path,
        **kwargs,
    )
